# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "headliner"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Patrick Crowley", "Alexander Shcherban"]
  s.date = "2012-01-24"
  s.description = "Assign and format page titles from your views"
  s.email = "shura.71@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "headliner.gemspec",
    "init.rb",
    "lib/headliner.rb",
    "pkg/headliner-0.1.1.gem",
    "spec/headliner_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/shura71/headliner"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Assign and format page titles from your views."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

